### ISSUE TITLE
Error in fms2_io/test_fms2_io: NetCDF: Not a valid data type or _FillValue type mismatch

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#490]
A few versions ago, netcdf-c added a check to ensure that fill values were the same type as the variable they are fill values for.

This was always supposed to be true, but the library did not check for it. Now it does. ;-(

Well that's a problem for FMS. I have seen this in my own testing, but now I also see it in fms2_io/test_fms2_io.sh:

```
(base) ed@mikado:~/FMS/test_fms/fms2_io$ bash -x ./test_fms2_io.sh
+ . ../test_common.sh
++ set -e
++ TEST_PASS=0
++ TEST_FAIL=1
++ TEST_SKIP=77
++ TEST_ERROR=99
++ top_srcdir=/home/ed/FMS
++ top_buildir=/home/ed/FMS
++ mpi_launcher=mpirun
++ oversubscribe=
+ printf 'EOF\n&dummy\nEOF'
+ cat
+ run_test test_fms2_io 6
+ test x = xskip
+ test xmpirun '!=' x
+ npes='-n 6'
+ mpirun -n 6 ./test_fms2_io
 Using            6  MPI ranks.
NOTE from PE     0: MPP_DOMAINS_SET_STACK_SIZE: stack size set to    32768.
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  Y-AXIS =   96
  X-AXIS =   96
  Y-AXIS =   96

FATAL from PE     0: NetCDF: Not a valid data type or _FillValue type mismatch


FATAL from PE     4: NetCDF: Not a valid data type or _FillValue type mismatch


FATAL from PE     0: NetCDF: Not a valid data type or _FillValue type mismatch


FATAL from PE     3: NetCDF: Not a valid data type or _FillValue type mismatch


FATAL from PE     2: NetCDF: Not a valid data type or _FillValue type mismatch


FATAL from PE     1: NetCDF: Not a valid data type or _FillValue type mismatch


FATAL from PE     5: NetCDF: Not a valid data type or _FillValue type mismatch

#0  0x7f1c899d3cd1 in ???
```

So somewhere in your I/O code you are setting a fill value which is a different type from the variable it applies to. Does anyone have an idea where this might be happening?

**Comment by uramirez8707** [comment]
@edwardhartnett 
1. Do you know in which version this check was added? 
2. Do you get a traceback? We do not add the fill value in any of the tests in test_fms2_io.F90 ...

**Comment by edwardhartnett** [comment]
I have asked the netCDF team about this, since I don't remember the precise details and I can't find mention of it in the RELEASE_NOTES. Follow the action here if interested: https://github.com/Unidata/netcdf-c/issues/1766.

I'll update this issue when I know more.

**Comment by edwardhartnett** [comment]
Here's the trace:

```
#0  0x7f364419bcd1 in ???
#0  0x7f89ac373cd1 in ???
#0  0x7f4ce9c97cd1 in ???
#1  0x56481a4d47f0 in __mpp_mod_MOD_mpp_error_basic
	at ../mpp/include/mpp_util_mpi.inc:70
#2  0x56481a7fa43c in __fms_io_utils_mod_MOD_error
	at /home/ed/f4/fms2_io/fms_io_utils.F90:164
#3  0x56481a82c4a0 in __netcdf_io_mod_MOD_check_netcdf_code
	at /home/ed/f4/fms2_io/netcdf_io.F90:284
#4  0x56481a80e0eb in __netcdf_io_mod_MOD_register_global_attribute_0d
	at /home/ed/f4/fms2_io/register_global_attribute.inc:60
#5  0x56481a445fe3 in atmosphere_restart_file
	at /home/ed/f4/test_fms/fms2_io/atmosphere_restart_file_test.inc:99
#6  0x56481a43d639 in MAIN__
	at /home/ed/f4/test_fms/fms2_io/test_fms2_io.F90:157
#7  0x56481a44f623 in main
	at /home/ed/f4/test_fms/fms2_io/test_fms2_io.F90:22
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
```

**Comment by edwardhartnett** [comment]
Not sure what is going on here. Seems to be attempting to write a longlong attribute. Why would that fail? I am going to try a run with netcdf logging turned on to see if that provides any more info...

**Comment by edwardhartnett** [comment]
I have looked into this with the other netCDF programmers and this is probably not related to fill value.

The fill value rule changes which I recalled had to do with DAP data, not disk data. So my problem here lies elsewhere. I will continue to investigate.

**Comment by menzel-gfdl** [comment]
@edhartnett, I don't think this error is FMS specific.  I was able to reproduce it with the code below.
This was built with ifort 19.1.2.254 20200623 and netcdf 4.7.4.

```
program main
use, intrinsic :: iso_fortran_env, only: error_unit, int64
use netcdf

integer :: err
integer(kind=int64) :: i
integer :: ncid

err = nf90_create("foo.nc", nf90_clobber, ncid)
i = 50
err = nf90_put_att(ncid, nf90_global, "att1", i)
if (err .ne. nf90_noerr) then
  write(error_unit, *) nf90_strerror(err)
  stop 1
endif
err = nf90_close(ncid)

end program main
```

**Comment by menzel-gfdl** [comment]
I have opened this [issue](https://github.com/Unidata/netcdf-c/issues/1807) in the netcdf-c repo.
