### ISSUE TITLE
test_fms/fms2_io/test_atmosphere_io fails when run...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#495]
There is a test, currently skipped, which, when I run, fails like this:

```
(base) ed@mikado:~/f4/test_fms/fms2_io$ bash -x ./test_atmosphere_io.sh
+ . ../test_common.sh
++ set -e
++ TEST_PASS=0
++ TEST_FAIL=1
++ TEST_SKIP=77
++ TEST_ERROR=99
++ top_srcdir=/home/ed/f4
++ top_buildir=/home/ed/f4
++ mpi_launcher=mpirun
++ oversubscribe=
+ printf 'EOF\n&dummy\nEOF'
+ cat
+ run_test test_atmosphere_io 6
+ test x = xskip
+ test xmpirun '!=' x
+ npes='-n 6'
+ mpirun -n 6 ./test_atmosphere_io
 Using            6  MPI ranks.
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
NOTE from PE     0: MPP_DOMAINS_SET_STACK_SIZE: stack size set to    32768.
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96

FATAL from PE     0: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     2: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     4: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     5: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     0: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     1: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     3: netcdf_file_open:: fms2_ncchksz not set.

#0  0x7fb508cfacd1 in ???
#0  0x7f4d98792cd1 in ???
#1  0x56111b901cd5 in __mpp_mod_MOD_mpp_error_basic
	at ../mpp/include/mpp_util_mpi.inc:70
#1  0x55dc69635cd5 in __mpp_mod_MOD_mpp_error_basic
	at ../mpp/include/mpp_util_mpi.inc:70
#0  0x7fc75a548cd1 in ???
#2  0x56111bc276c5 in __fms_io_utils_mod_MOD_error
	at /home/ed/f4/fms2_io/fms_io_utils.F90:164
#2  0x55dc6995b6c5 in __fms_io_utils_mod_MOD_error
	at /home/ed/f4/fms2_io/fms_io_utils.F90:164
#3  0x56111bc583df in __netcdf_io_mod_MOD_netcdf_file_open
	at /home/ed/f4/fms2_io/netcdf_io.F90:499
#3  0x55dc6998c3df in __netcdf_io_mod_MOD_netcdf_file_open
	at /home/ed/f4/fms2_io/netcdf_io.F90:499
#4  0x56111bc8422a in __fms_netcdf_domain_io_mod_MOD_open_domain_file
	at /home/ed/f4/fms2_io/fms_netcdf_domain_io.F90:379
#4  0x55dc699b822a in __fms_netcdf_domain_io_mod_MOD_open_domain_file
	at /home/ed/f4/fms2_io/fms_netcdf_domain_io.F90:379
#5  0x56111b8736ae in test_atmosphere_io
	at /home/ed/f4/test_fms/fms2_io/test_atmosphere_io.F90:113
#6  0x56111b87cb08 in main
	at /home/ed/f4/test_fms/fms2_io/test_atmosphere_io.F90:22
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
#5  0x55dc695a76ae in test_atmosphere_io
	at /home/ed/f4/test_fms/fms2_io/test_atmosphere_io.F90:113
#6  0x55dc695b0b08 in main
	at /home/ed/f4/test_fms/fms2_io/test_atmosphere_io.F90:22
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
```

This seems to be an initialization problem.

The "skip" option in your testing has allowed a lot of programmers to check in a lot of broken tests, and then skip them. This is the worst of all worlds - you are paying someone to write test code, but not getting any value out of that code, because you are skipping it. Also, your product is still untested. 

So let's get this test working, and start getting some value out of it.

**Comment by thomas-robinson** [comment]
@rem1776 is working on this

**Comment by rem1776** [comment]
In #507 I added a missing initialization call that was causing the atmosphere test to fail, but this seemed to cause test_fms2_io to fail instead.

**Comment by edwardhartnett** [comment]
It seems like there's lots of tests succeeding, and one or more failing.

I suggest you comment out the failing tests, and try and get the resulting PR through testing and review, and get it merged. Then circle back around and work on the broken tests incrementally.

Currently, there is a lot of good test code going to waste. Get it in service, and you will prevent yourself and others from inadvertently breaking some IO code. The working tests are not testing everything you want, but they are testing a lot.
